### ISSUE TITLE
slickAdd and slickRemove methods not implemented

### ISSUE THREAD

**Issue by laveesingh** [akiran/react-slick#1061]

**Comment by laveesingh** [comment]
Not going to be implemented, the same functionality can be achieved as with dynamic slides. See dynamic slides example.

**Comment by Mr-Chilly** [comment]
tbh I'm not sure this is correct. I am trying to add and remove a slide for opposite ends of an array:

`[0,1,**2**,3,4] => [1,2,**3**,4,5]` but I've no control over the index slide, so in actual fact I end up with:`[0,1,**2**,3,4] => [1,2,3,**4**,5]`

Changing the array seems ok, but without actually having control over `slideIndex` as in the vanilla slicks add/remove examples

**Comment by laveesingh** [comment]
I'm not sure I understand your query, but Dynamic Slides example should help you.

**Comment by Mr-Chilly** [comment]
Sorry I'll try and be more clear...

https://codesandbox.io/s/z3yy44vyyp

I need to load new content into the slides, and remove old content (see ternary switch swapping the arrays in the example). However whenever I load more content in, I still need the active slide (the center one) to be in the same position. currently, it'll shift one to the 'right' 

(imagine here I'm loading the content on each progression, rather than a button click)

With access to the `slideIndex` I can manually update this; setting the index slide 'back' one - giving the illusion that nothing has changed in the slider:

[*1*, 2, 3, 4, 5] = 1 is active, user progresses to slide 2
[1, *2*, 3, 4, 5] = 2 is now active, so load new content...
[2, *3*, 4, 5, 6] = 3 is now active... 

Dynamic slides works very well in situations where the fundamental slides don't, however removing slides doesn't keep the index correctly.

If I can change the `slideIndex`, or even `activeSlide` this would be trivial!
