### ISSUE TITLE
Option to Keep dots on the left or right Vertically

### ISSUE THREAD

**Issue by cjithu** [akiran/react-slick#1108]
Is there a possibility to keep the dots on the left or right so that, vertical scroll towards end of section moving to next section either up or down.

Can anyone help to create something like that.

**Comment by laveesingh** [comment]
I believe you can achieve that with `dotsClass` prop and custom CSS.

**Comment by ozgurshn** [comment]
You can achieve vertical dots on right side like this:
Set this property in settings.
dotsClass:"vertical-dots"

in slick-theme.css add Css below
.vertical-dots
{
    right:10px;
    list-style: none;
    display: block;
    position: absolute;
    top: 40%;
    margin-top: -10px;
    text-align: right;
}
.vertical-dots li
{
    position: relative;
    width: 20px;
    height: 20px;
    cursor: pointer;
}
.vertical-dots li button
{
    font-size: 0;
    line-height: 0;
    display: block;
    width: 20px;
    height: 20px;
    padding: 5px;
    cursor: pointer;
    color: transparent;
    border: 0;
    outline: none;
    background: transparent;
}
.vertical-dots li button:hover,
.vertical-dots li button:focus
{
    outline: none;
}
.vertical-dots li button:hover:before,
.vertical-dots li button:focus:before
{
    opacity: 1;
}
.vertical-dots li button:before
{
    font-family: 'slick';
    font-size: 6px;
    line-height: 20px;

    position: absolute;
    top: 0;
    left: 0;

    width: 20px;
    height: 20px;

    content: '•';
    text-align: center;

    opacity: .25;
    color: black;

    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
.vertical-dots li.slick-active button:before
{
    opacity: .75;
    color: black;
}

**Comment by dominiquevidovic** [comment]
Hi,

This is a closed issue, however for those who are using react-slick out of the box, I was able to vertically align the dots by amending the appendDots and customPaging properties of the Slider component without amending the slick-theme.css.

**Placement and vertically align dots:**
For the appendDots property; the two CSS styling properties for the UL element placement is the top and right, the value depends on your slide's content.  Also to vertically align the LI elements, you will need to set the CSS display property to 'list-item'

**Using react-slick behaviour of when an item is selected (when you have amended the appendDots property).**
To continue to use the 'slick-active' CSS styling, I had to add an extra UL and LI around the button and set the className of LI to 'slick-active'.  The reason I had to add an extra UL and LI elements is due to the outer element around the button was a LI.

 appendDots: dots => {
            return (
                <ul className="slick-dots" style={{ top: "20%", right: "-100%"}}>
                    {dots.map((item, index) => {
                        return (
                            <li key={index} style={{ display: "list-item", paddingBottom: "2%"}}>{item.props.children}</li>
                        );
                    })}
                </ul>
            )
        },
customPaging: index => {
            return (
                <ul>
                    <li className={index === currentSlide ? "slick-active" : null}>
                        <button>
                            {index + 1}
                        </button>
                    </li>
                </ul>
            )
        }

Note, my component is a function and not a class, which has a reference to the Slider component and I am using the useState hook to store the currentSlide.
