### ISSUE TITLE
ios click not working 

### ISSUE THREAD

**Issue by virajs07** [akiran/react-slick#1175]
Thanks for this amazing slider. We are using this very frequently but we found that on ios whether or chrome or safari click events on image which are part of carousel is not working. This issue is pretty specific to ios on all iphones and not happening on desktop or android. This has happened in your 0.21 or 0.20 build because it was working fine till 0.19.

**Comment by victsant** [comment]
@virajs07 
Did you figure out what was wrong?

**Comment by virajs07** [comment]
@victsant I had by mistake closed this issue. But we shifted to the previous version to make it work. Haven't found the reason for that. I will reopen the issue

**Comment by thuctonhuyen** [comment]
Hi! I have the same issue on version 0.23.1. The click event on image is not triggered. I have surrounding the image with <Link> to navigate to some pages. It works fine on desktop; however, it does not work at all on ios.

**Comment by Jimi6** [comment]
Which version?@virajs07

**Comment by arteagabriel** [comment]
@virajs07 I was running into a similar issue where I had an on click event on a slide, but on iOS if you clicked on an image within the slide it didn't work. I found a workaround where I wrapped the image in the slide within a div and added pointer-events: none to the image itself. I added cursor: pointer to the image wrapper because of [this](https://github.com/facebook/react/issues/7635) but not sure if that part was necessary.

**Comment by AmaanKulshreshtha** [comment]
I had the same issue, but my `<img>` tag was inside an `<a>` tag. As @arteagabriel said, adding `pointer-events: none` to the `<img>` tag did the trick, but then it broke in IE-11. 
So in order to make it work in both places, I added a `display: block` to the `<a>` tag.

**Comment by sanmaopep** [comment]
I've also faced the same situation in iphone6 ios10 recently @thuctonhuyen , but it's fixed when it navigate to iphone 8+ ios 13.
