### ISSUE TITLE
CurrentSlide and slideCount Warnings still in v 0.23.1

### ISSUE THREAD

**Issue by waheed25** [akiran/react-slick#1238]
I am still getting these warnings i am passing arrow like this
`prevArrow: LeftArrow(), `
LeftArrow is a svg icon.

**Comment by yoyo837** [comment]
Yes，it's work. https://github.com/akiran/react-slick/issues/728#issuecomment-310773471

**Comment by AgainPsychoX** [comment]
I have the same issue I guess?

**Comment by AgainPsychoX** [comment]
In DOM tree (Chrome DevTools):
![image](https://user-images.githubusercontent.com/23557839/124244389-2e2b7080-db1f-11eb-87d0-3129d5f9db6b.png)

Errors (Chrome console):
![image](https://user-images.githubusercontent.com/23557839/124244460-40a5aa00-db1f-11eb-8e4b-3e85d6615b2c.png)


Used settings for Slider:
```
				infinite 
				speed={500}
				slidesToShow={3}
				slidesToScroll={1}
				responsive={[
					{breakpoint: 1200, settings: {
						slidesToShow: 2,
					}},
					{breakpoint: 940, settings: {
						slidesToShow: 1,
					}},
				]}
				arrows
				nextArrow={
					<div>
						<NavigateNext fontSize="inherit"/>
					</div>
				}
				prevArrow={
					<div>
						<NavigateBefore fontSize="inherit"/>
					</div>
				}
```

The `NavigateBefore`/`NavigateNext` are SVGs, nevertheless I packed those in `div`s since I got some other problems (see issue #2051 )
