### ISSUE TITLE
variableWidth and left issue

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [akiran/react-slick#1304]
Hi guys,

My carousel is "full screen" meaning that it is pushed to the left and top with width 100% + pushed difference width and position absolute. Pushed from its original place. In order to have slides working properly I use `variableWidth: true`, but value is not taken into consideration when it calcs left offset.

**Current behavior**:
With `variableWidth: true` and width of container 150 it slides to 130 left because it is original width of container not that, which is set by `variableWidth`.

**Expected behavior**:
With `variableWidth: true` and width of container 150 it slides to 150 taking into account container width, which is set by `variableWidth`.

**Comment by dm-randy** [comment]
This sounds like it might be the same issue that I'm encountering. Here is a codesandbox example: https://codesandbox.io/s/9yww1028o4.

For best results, open the preview pane in a new window. Note that, even though there are 10 slides, only 8 (or fewer) are displayed. This is slightly different from #1230 because in addition to not being able to scroll to the final slide, the user cannot even see the slide. At some widths, the user can even scroll through empty slides.

**Comment by randallreedjr** [comment]
This sounds like it might be the same issue that I'm encountering. Here is a codesandbox example: https://codesandbox.io/s/w0o673l835.

For best results, open the preview pane in a new window. Note that, even though there are 10 slides, only 8 (or fewer) are displayed. This is slightly different from #1230 because in addition to not being able to scroll to the final slide, the user cannot even see the slide. At some widths, the user can even scroll through empty slides.
