### ISSUE TITLE
Slider giving `NaN` is an invalid value for the `top` css style property.

### ISSUE THREAD

**Issue by smasinde** [akiran/react-slick#1310]
https://codesandbox.io/s/kk3mpx80z5

If you look at the console im getting: 
```
Warning: `NaN` is an invalid value for the `top` css style property.


Check the render method of `Slider`.
```

**Comment by EmilTholin** [comment]
[`slideHeight` is used when you use the `vertical` and `fade` props](https://github.com/akiran/react-slick/blob/5591aab45d6c9fdc62e25fdfcf81d0c84d60764c/src/track.js#L56) on the slider, but [`slideHeight` is not set until `componentDidMount`](https://github.com/akiran/react-slick/blob/be952ad7c8ae400854cc11d668870bf1bd8fa0a8/src/inner-slider.js#L75) of the `InnerSlider` component, which means that `style.top` will be set to `NaN` on the first render. It's probably a bug, but not a problem since it updates right away. It might work if [`slideHeight` is initialized to 0 instead of `null`](https://github.com/akiran/react-slick/blob/48c93ed36cfb58991e6bf4d34a1a588094281d12/src/initial-state.js#L16), but I don't know for sure.

**Comment by axebox** [comment]
I reproduced this as well. Working around it for now.

**Comment by Yeswanth-JG** [comment]
I am getting similar issue.... 

But I am getting the error for the 'left' property. Below is the full error trace.

**But the plugin works.**
```
    Warning: `NaN` is an invalid value for the `left` css style property.
    in div (created by Slider)
    in div (created by Track)
    in Track (created by InnerSlider)
    in div (created by InnerSlider)
    in div (created by InnerSlider)
    in InnerSlider (created by Slider)
    in Slider (at sliderLayout.js:99)
    in div (at sliderLayout.js:98)
    in SliderLayer (at Home.js:20)
    in div (at Home.js:19)
    in Home (created by Route)
```

I am using below versions of the s/w.

```json
    "react-slick": "^0.26.1",
    "slick-carousel": "^1.8.1"
````

**Comment by Yeswanth-JG** [comment]
> I am getting similar issue....
> 
> But I am getting the error for the 'left' property. Below is the full error trace.
> 
> **But the plugin works.**
> 
> ```
>     Warning: `NaN` is an invalid value for the `left` css style property.
>     in div (created by Slider)
>     in div (created by Track)
>     in Track (created by InnerSlider)
>     in div (created by InnerSlider)
>     in div (created by InnerSlider)
>     in InnerSlider (created by Slider)
>     in Slider (at sliderLayout.js:99)
>     in div (at sliderLayout.js:98)
>     in SliderLayer (at Home.js:20)
>     in div (at Home.js:19)
>     in Home (created by Route)
> ```
> 
> I am using below versions of the s/w.
> 
> ```json
>     "react-slick": "^0.26.1",
>     "slick-carousel": "^1.8.1"
> ```

This issue is coming for me in my project. But this issue is not coming up in the online playground, where we are using React DOM attachment in the same file. 

In our project, we are using the react DOM hooking in the root js.
