### ISSUE TITLE
include css and fonts files

### ISSUE THREAD

**Issue by jmgarciamari** [akiran/react-slick#14]
How I can to include css and fonts files in my react-project?There Are on node_modules, I think. But I don't know how to include them.

Thanks

**Comment by akiran** [comment]
you should use slick carousel for slick-carousel
```bash
bower install slick-carousel
```
or link to cdn version
https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.15/slick.css

**Comment by harryworld** [comment]
Should I copy the `fonts` and `ajax-loader.gif` manually, or I have a way to import that from `bower` using webpack?

**Comment by vramana** [comment]
@harryworld We don't use ajax-loader.gif. We use fonts for Arrow icons. You can avoid fonts by using your own custom components. So, don't bother with that.

Hey, I am writing a more modern version of slick using flexbox [here][react-flex-slick]. It is pretty bare minimum at the moment because I literally started working on it today. You can try it out if you want. Ask for any features. It'll try to quickly bootstrap them. 

[react-flex-slick]: https://github.com/vramana/react-flex-slick

**Comment by harryworld** [comment]
@vramana thanks for the quick reply, definitely will take a look.
