### ISSUE TITLE
Prevent automatic scroll to viewport on slide

### ISSUE THREAD

**Issue by liorix** [akiran/react-slick#1522]
Hi,

Is there a setting that I can use to disable the automatic scroll of the slider into the viewport upon a click event on one of the slider images? 

Video with example:
https://cl.ly/d883580953e1

The code here:
https://codesandbox.io/s/8l4xom9398

Many thanks,
Lior

**Comment by googabeast** [comment]
There is no true setting for this that I have found, the reason it is happening in your case is because when you trigger the next slide event the script is designed to slide in the new container and set .focus() to the new slide. 

Because in your instance you do not have the entire slider within the viewport the browser interprets this as a scroll to the newly focused element.

focusOnSelect: false

Will correct the .focus() issue, but seems to disable the click event for next/prev slide, however swipe seems to still work.

**Comment by liorix** [comment]
Thanks so much @googabeast, that was very helpful. I just created a patch that runs automatically  and remove the focus() code.  
Thanks again,
Lior

**Comment by Prottoy2938** [comment]
I'm having a similar issue. For me, the component fetches images from an  API and when those new images are rendered, the carousel unexpectedly comes to the viewport. 

For example, if the user was scrolling down to see some other content while the images are loading, then when the loading is finished and the new images are rendered, the carousel comes to the viewport, scrolling back the user expectedly 


How to prevent this?

**Comment by tsarma** [comment]
Now a days you can use `focusOnChange: false` in options.

**Comment by achicyr** [comment]
if i do no put any setting object, or put full option, it behave exactly the same ....
