### ISSUE TITLE
How to set height of all elements by most large height.

### ISSUE THREAD

**Issue by prodev903** [akiran/react-slick#1539]
https://jsfiddle.net/JJaun/o29a4q45/

How to implement in react

**Comment by udayRedI** [comment]
Any solutions/workarounds?

**Comment by akiran** [comment]
This is not a carousel specific problem

**Comment by samturner3** [comment]
it is. Only way is to set `rows: 0` as seen resolved in ☝️  [jsfiddle](https://jsfiddle.net/JJaun/o29a4q45/) that is now implemented using **_slick.js_** (not **react-slick**). 

But does not work with **react-slick** due to [this issue](https://github.com/akiran/react-slick/issues/1254) where now setting `rows: 0` crashes the app.

A fix with issue [#1254](https://github.com/akiran/react-slick/issues/1254) will hopefully resolve this.

Unless you can demonstrate any other way??

**Comment by ike-ko** [comment]
For my own purposes I was able to set height of elements to largest height with this css:

`.slick-track {
    display: flex;

    .slick-slide {
        height: auto;
        display: flex;

        > div {
            display: flex;
            width: 100%;
        }
    }
}`

**Comment by Span415** [comment]
> For my own purposes I was able to set height of elements to largest height with this css:
> 
> ```
> .slick-track {
>     display: flex;
> 
>     .slick-slide {
>         height: auto;
>         display: flex;
> 
>         > div {
>             display: flex;
>         }
>     }
> }
> ```

Thank you so much, my friend! It works!

**Comment by AlvaroDeen** [comment]
> For my own purposes I was able to set height of elements to largest height with this css:
> 
> ```
> .slick-track {
>     display: flex;
> 
>     .slick-slide {
>         height: auto;
>         display: flex;
> 
>         > div {
>             display: flex;
>         }
>     }
> }
> ```

Save my day!
tks!

**Comment by longnguyendev** [comment]
I love you 3000

**Comment by longnguyendev** [comment]
> For my own purposes I was able to set height of elements to largest height with this css:
> 
> ```
> .slick-track {
>     display: flex;
> 
>     .slick-slide {
>         height: auto;
>         display: flex;
> 
>         > div {
>             display: flex;
>         }
>     }
> }
> ```

i love you 3000
