### ISSUE TITLE
customPaging

### ISSUE THREAD

**Issue by flowdee** [akiran/react-slick#16]
Do you think about integrating Slick's **customPaging** functionality?

This would be great! :thumbsup:

**Comment by akiran** [comment]
Yes, I will try to implement it this weekend.

or If possible, can you try to implement and submit a pull request

**Comment by flowdee** [comment]
Thanks for your quick reply akiran. Would be awesome if you implement this as soon as possible!

**Comment by akiran** [comment]
ok

**Comment by flowdee** [comment]
Any updates here @akiran ? Did you find time to test the implementation yet?

**Comment by rockymadden** [comment]
@flowdee and @akiran, see https://github.com/akiran/react-slick/pull/36

**Comment by flowdee** [comment]
thanks

**Comment by akiran** [comment]
@rockymadden  Thanks for the pull request.
I will review it and merge soon

**Comment by dra1n** [comment]
customPaging function in default-props is barely usable. It has signature function(onClick, i, element), but in Dots component there is call this.props.customPaging(i)

**Comment by akiran** [comment]
customPaging implementation is still under review. 
Even I am not fully confident about the current implementation. Hence not published it yet.

Welcome PR's and suggestions

**Comment by akiran** [comment]
@dra1n  Fixed the customPaging default prop issue.

**Comment by dra1n** [comment]
Hello! Strange things I have version "0.14.3" and customPaging is already
implemented and works almost fine.

But to the point. Function in default-props still uses onClick var which is
undefined now. This won't cause an error only because onClick will be
overridden when we are creating dot element in dots.jsx {React.cloneElement(
this.props.customPaging(i), {onClick})} So it would be better to leave
default button like this <button>{i + 1}</button>

Sorry for being lazy and not sending PR on this.

2016-09-16 14:24 GMT+03:00 Kiran <notifications@github.com>:

**Comment by akiran** [comment]
Fixed it in 0.14.4
