### ISSUE TITLE
Can't click to next or previous slide if fade is `true` and infinite is `false`

### ISSUE THREAD

**Issue by joeyprint** [akiran/react-slick#1881]
### Can't click next or previous button

If the setting option components like ...

```js
const setting = {
  fade: true,
  infinite: false,
}
```

You can only click the next slide button from the first slide to the second slide. In addition, you will found it can't click the next slide after the second slide.

In the example, I add option `dots: true` for giving to test.
_(Dots is working, but button isn't work)_

**Example:**
[https://codesandbox.io/s/react-slick-playground-forked-fd3j4?file=/index.js](https://codesandbox.io/s/react-slick-playground-forked-fd3j4?file=/index.js)

**Comment by gautamz07** [comment]
@akiran this seems to be due to a piece of code you added recently [here](https://github.com/akiran/react-slick/blame/master/src/utils/innerSliderUtils.js#L287). 

`
if (!infinite) {
   targetSlide = previousTargetSlide + slidesToScroll;
}
`

Would be helpful if you add the bug id in your commit messages, so the reason for the fix becomes apparent. Do you plan to revert the fix or at least could you post the ticket for why this fix was added ? LMK.

**Comment by akiran** [comment]
@gautamz07 That fix is to make slide navigation with keyboard arrows work.

**Comment by gautamz07** [comment]
@akiran , 

investigated this issue is bit , any obvious reason why you decided to use `targetSlide: previousTargetSlide` instead of just using `currentSlide` , which is already being reliably used in the changeSlide function ?

using `currentSlide` seems to get the functionality back on track. 

If you have a commit id for this change you introduced and the commit fixes 1 specific issue only , I can create a PR with a `git revert` commit and add the change. let me know.

**Comment by akiran** [comment]
No need to revert.

Please create a new PR with the fix
