### ISSUE TITLE
Nested components

### ISSUE THREAD

**Issue by AndonMitev** [akiran/react-slick#1923]
Hello i have following code example:

```
 <SliderWrapper>
        <Login  />
</SliderWrapper>
```
And login component returns:
`{loginTypes.map(type => <div key={type}>{type}</div>)}`

OR is there any Workaround so I can achieve this structure

**Comment by akiran** [comment]
This slider works by cloning children to add additional properties. So slides should be children of Slider.
Slides can't be in nested components.

You have to refactor your components to put slides directly under Slider.

Please stopping re-opening the same issue again.
It can't be fixed in this library.
