### ISSUE TITLE
Can't put background image with lower z-index between container and carousel.

### ISSUE THREAD

**Issue by RemyMachado** [akiran/react-slick#1938]
Hello, the carousel stops working when I got this configuration: relative container > absolute bg-image > carousel

I'm not sure why the z-indexes are breaking the component. Is it desired behavior and do I need to do something else to get it working ?

Here's the bug example: https://codesandbox.io/s/react-slick-playground-forked-b9bp7

**Comment by JerryK026** [comment]
It's might because CSS & JavaScript's philosophy & logic's problem.

every element has z-index property and It's 0 as default.

u give -1 and -2 z-index to img and bg-img. and it of course wouldn't work.

it is like you can't draw something on a paper right under a desk.

and if you have smaller size bg-img than img, you can draw something.

because bg-img can't cover whole the img.

here is a picture for your understand.

white paper : img, hatched paper : bg-img, desk : 0 z-index elements

![explain](https://user-images.githubusercontent.com/55067949/101160390-4cf18380-3672-11eb-9e3e-fdd1096f74b6.png)

I hope to it can help you! 👍  :)

**Comment by JerryK026** [comment]
So if you give z-index to img -> 0 and bg-img -> 1,

you can solve this problem!!!

**Comment by RemyMachado** [comment]
@JerryK026 Thank you for your response. You may have swapped variable names in your explication making it not staightforward, but it was very helpful.

I managed to make it work by removing negative indices as you suggested:

container: 0
bg-img: 1
carousel: 2
