### ISSUE TITLE
Blur effect in Chrome 88

### ISSUE THREAD

**Issue by G0TT0N** [akiran/react-slick#1975]
As you may have noticed from your own examples page, after updating Chrome browser to version 88, your carousel began to disintegrate into pixels after swiping the slides.
I checked through browserstack, everything works correctly on version 87 and in beta version 89. The bug is only 88. What should we do? Our sites are broken.

**Comment by tgldr** [comment]
I got the same issue in v88.

**Comment by dlong500** [comment]
I get serious distortions during slide transitions in Chrome with any version after 87.  Chrome Beta 89.0.4389.23 does NOT fix the issue for me.  It reminds me of some issues about 5-6 years ago related to `translate3d` but obviously those particular issues were resolved.  This is disturbing since it has made in all the way to a production Chrome release.  Edge 88.0.705.56 also exhibits this problem.

I even removed any text and I can still see serious distortion/blurriness even with just an image sliding.  There is a noticeable jarring crisp to blurry shift when the slide animation starts, and then a similar blurry to crisp shift when the animation stops.

As of right now I can't even seem to get the Chromium Bugs page (https://bugs.chromium.org/p/chromium/issues/list) to load (there seems to be a known issue with Monorail), and I'm also having difficulty finding any helpful info in general web searches.

Here is a codepen of a basic test (this is just a simple JPEG): https://codepen.io/dlong500/pen/dyOydZE

<details>
  <summary>Here is an animated gif of the test running under Chrome 87 with proper transitioning (Click to expand):</summary>
  
  ![proper-transitions](https://user-images.githubusercontent.com/430481/106324407-15a0ec80-6247-11eb-893b-8f4299ba3194.gif)
</details>

<details>
  <summary>Here is an animated gif of the test running under Chrome 88/89 with blurry transitioning (Click to expand):</summary>
  
  ![blurry-transitions](https://user-images.githubusercontent.com/430481/106324492-3b2df600-6247-11eb-9109-e24a0b26b0b7.gif)
</details>

**Comment by G0TT0N** [comment]
> I get serious distortions during slide transitions in Chrome with any version after 87. Chrome Beta 89.0.4389.23 does NOT fix the issue for me. It reminds me of some issues about 5-6 years ago related to `translate3d` but obviously those particular issues were resolved. This is disturbing since it has made in all the way to a production Chrome release. Edge 88.0.705.56 also exhibits this problem.
> 
> I even removed any text and I can still see serious distortion/blurriness even with just an image sliding. There is a noticeable jarring crisp to blurry shift when the slide animation starts, and then a similar blurry to crisp shift when the animation stops.
> 
> As of right now I can't even seem to get the Chromium Bugs page (https://bugs.chromium.org/p/chromium/issues/list) to load (there seems to be a known issue with Monorail), and I'm also having difficulty finding any helpful info in general web searches.
> 
> Here is a codepen of a basic test (this is just a simple JPEG): https://codepen.io/dlong500/pen/dyOydZE
> 
> Here is an animated gif of the test running under Chrome 87 with proper transitioning (Click to expand):
> Here is an animated gif of the test running under Chrome 88/89 with blurry transitioning (Click to expand):

**Comment by G0TT0N** [comment]
@dlong500, I tested version 89 via BrowserStack. Perhaps the bug has not been fixed in a real browser. Bad.. I don't even know what to do. I don't want to rewrite the project at all.

P.S. Was closed by mistake. I missed the button.

**Comment by douglasrcjames** [comment]
Also getting this with my image slider on Chrome Version 88.0.4324.150 (Official Build) (64-bit). Bug not showing up on Firefox.
![image](https://user-images.githubusercontent.com/22306305/107090860-b0547a80-67b5-11eb-9f15-bc3833ea44b6.png)

**Comment by bunea** [comment]
It seems like this [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1172666&q=transition&can=2) is probably related to this.

For my use case applying in css `will-change: transform` to the class `slick-list` seems to have fixed it. I'm leaving this here in case it might help anyone else facing the same problem.

**Comment by douglasrcjames** [comment]
@bunea thanks mate! That worked for me.

**Comment by G0TT0N** [comment]
> It seems like this [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1172666&q=transition&can=2) is probably related to this.
> 
> For my use case applying in css `will-change: transform` to the class `slick-track` seems to have fixed it. I'm leaving this here in case it might help anyone else facing the same problem.

Yes, it works. Thank you!

**Comment by dlong500** [comment]
For what it's worth it looks like the Chrome developers resolved this issue (I just tested Chrome v89.0.4389.82).  The issue linked to by @G0TT0N was resolved around the second week of February.  This is great because the `will-change: transform` workaround has a lot of other bad side-effects (such as causing elements to disappear during animations).
