### ISSUE TITLE
React dots not match in center mode

### ISSUE THREAD

**Issue by ciplnaveen** [akiran/react-slick#2011]
### Dots are not in sync with slides
I have total **4** slides and the visible dots are just **2** in this case(*so it only clicks twice*), I need to show 3 slides in the frame, my settings are:

**const settings = {
    dots: true,
    className: 'center',
    centerMode: true,
    infinite: false,
    arrows: false,
    slidesToShow: 3,
    slidesToScroll: 1,
  };**

When i set **infinite:true** then it shows 4 dots which is not the required case.
How to keep infinite off and keep the dots synced with slides & shows 3 slides in frame.

**Comment by Iwi4a** [comment]
@ciplnaveen The reason you are getting two dots is because the second frame shows all of your elements in view, this is also why it works with infiniteScroll (there are more frames after your 4th element). A workaround this could be to render your dots separately and then to use the [methods from the docs](https://react-slick.neostack.com/docs/api#slickGoTo) to add functionality. 

When the third element is active, do you need to have the second off of the view?

**Comment by ciplnaveen** [comment]
@Iwi4a Thanks for the feedback, and no i don't want my 2nd slider to drop off when third is active, just wanted to move it to left.

**Comment by Iwi4a** [comment]
@ciplnaveen I do not think react-slick can solve this use case the way you want it by itself, correct me if I am wrong, it sounds like you are trying to highlight the elements in the slides rather than the slides. I would suggest you to approach this by using the dots to select the elements (each element has its own unique data-index) and depending on which dot was clicked, use **slickGoTo** to slide to that frame.
