### ISSUE TITLE
Using adaptiveHeight: true produces error.

### ISSUE THREAD

**Issue by nackjicholson** [akiran/react-slick#252]
Using

react-slick@0.11.0
slick-carousel@1.5.9 for the CSS

Settings:

```js
{
  const slickSettings = {
    dots: true,
    infinite: true,
    arrows: false,
    adaptiveHeight: true
  };
}
```

The following error comes from

helpers.js:89

```
Uncaught TypeError: Cannot read property 'offsetHeight' of null
```

**Comment by akiran** [comment]
I couldn't replicate this issue. Its working fine with the given settings.
Check this demo https://jsfiddle.net/kirana/wna3a6q5/

**Comment by Yoanns** [comment]
@akiran @nackjicholson 
Guys, I believe I found out what the issue is since I have been dealing with the exact same error. @akiran in your example, your images are loaded as soon as your react component is call. However, in React, there are situations were the data is set empty in an initial state and then when componentDidMount() fires there is an ajax call or or any other way you want to use to set the data.

I replicated the error in [here](https://jsfiddle.net/New_user8/xqtqdb4x/4/) based on something I am working on (inspect your page to see the logs I left).

The simplest way to fix this is display the data only if the data is not empty like I did in [this other example](https://jsfiddle.net/New_user8/xqtqdb4x/3/)
You just need to replace your initial slider tag
`<Slider {...settings}>
						{allPosts}
					</Slider>`

by the the following

`{this.state.posts.length > 0 ?
					<Slider {...settings}>
						{allPosts}
					</Slider>
				: 
					<div className="placeholder">
						No Posts
					</div>
				}	`

I hope this helps.

Cheers

PS: For some reason my images don't display here, but they do on my project and the error doesn't show up anymore.

**Comment by bnolens** [comment]
Make sure `data-index` is set and is an integer. And if your slide is a component, make sure to set the `data-index` attribute to the root element of your slide component. 

Your slide component could look something like this:
```
const Slide = ({ dataIndex }) => {
    return(
        <div data-index={dataIndex} key={dataIndex}>
            <p>Slide {dataIndex}</p>
        </div>
    )
}
```

This fixed it for me.
