### ISSUE TITLE
Slick and Bootstrap Tabs

### ISSUE THREAD

**Issue by mycroft11** [akiran/react-slick#266]
Hi! 

Is there a way to force a recreate of the component? Something like destory() and init()? I am using multiple sliders inside different bootstrap tabs, but the ones in the hidden tabs don't get rendered properly (the slides are rendered vertically instead of horizontally)

Any ideas?

Thank you.

**Comment by talbenbasat** [comment]
@akiran  any update on this issue?

**Comment by talbenbasat** [comment]
HI @mycroft11 ,

I manged to figure this out.

since the tab is with a 0 width then the component rendering doesnt work well.

I managed to hook on the onEnter callback of the tab and display the slider only when the tab is active.
In this case the tab width will be correct and the slider will render correctly

Tal

**Comment by mohandere** [comment]
HI @talbenbasat 

i have same problem, can you please paste the code snippet here ?

Thank you in advance.

**Comment by mohandere** [comment]
Hi @talbenbasat 

I managed this with - 

`componentDidMount() { setTimeout(() => { window.dispatchEvent(new Event('resize')) }, 0); }`

**Comment by laveesingh** [comment]
This issue has been fixed couple of releases back. Please feel free to request reopen if disagree.
