### ISSUE TITLE
How do I actually use this?

### ISSUE THREAD

**Issue by mingfang** [akiran/react-slick#3]
The example on the github page does not even compiler due to this ```...{setting}```.
I can't fine the react-slider.js anyway but managed to cut and paste it from ```http://webrafter.com/opensource/react-slick``` by viewing the source.
But even then, I'm getting this error at runtime
``` Uncaught ReferenceError: webpackJsonp is not definedreact-slick.js:1 (anonymous function)```

**Comment by akiran** [comment]
As of now you have to use a build tool like browserify or webpack.
This [yeoman generator](https://github.com/akiran/generator-react-slick.git) help you setup quickly.

{...settings} is es6 feature and require react 0.12
If you are using jsx loader add harmony flag and if you are using reactify add {es6: true}  to your browserify config

I am not providing react-slider.js because it is a good practice to  avoid exposing react component on global and it is better to use a build tool.

Let me know your feedback.

**Comment by mingfang** [comment]
Thanks for the response.
Unfortunately I'm a server guy and do not know anything about front end stacks, therefore I have not idea what to do next.
Take jquery.js for example. 
I'm able to just point to it using a ```script``` tag and use it straight away, without having to build it.
That seems much for user friendly.
Closing since it appears to work for you.

**Comment by akiran** [comment]
If you work on server (Java, ruby or python etc) you must be already familiar with module system.
Same sort of module system can be used Javascript.

Jquery uses globals because at the time of its creation there was no module system and build tools
Now javascript is maturing and borrowing ideas like module system from server side languages like python, ruby. 

I haven't provided bundled packages because it is not a good practice now.
You will loving using a build system after passing the initial setup hurdle.
let me know if you need help in setting up.

Just curious. Are you able able to find bundled packages for other opensource react components?
