### ISSUE TITLE
Page Count

### ISSUE THREAD

**Issue by shprink** [akiran/react-slick#315]
Hi,

is it possible to get the total number of pages and current page so we could display pagination?

`page: 3/10`

Thanks

**Comment by akiran** [comment]
You can use beforeChange/afterChange methods to get the current slide number.
You can compute total pages based on you slide count

**Comment by shprink** [comment]
actually if you use the responsive layout, the number of page changes. 

You must have this data internally so it would be good to share it through afterChange event don't you think?

want a PR?

**Comment by akiran** [comment]
Even in responsive, it changes according to settings you pass.
So, You will have that info already

**Comment by paschalidi** [comment]
Hello, 
I do not get how to show only one pagination number at the time and as many as the items I have on the slider. 

I mean when I have 4 items I wanna show x/4, not 1/4  2/4  3/4  4/4 . 

Is this possible ?

**Comment by aliakseikrauchanka** [comment]
@akiran  I think it make sense to provide total page number cause otherwise 
1) we need to mirror the same logic which is already inside react-slick component which seems to be strange.
2) if for some reason logic calculating pages inside react-slick changes we always need to keep track on these changes and update logic on our end accordingly.

Please share your opinion on that

**Comment by DavidDolyak** [comment]
Had the same issue :)) This is my solution
```
 afterChange={(current) => {
       const pageCount = document.querySelector('.slick-track')?.childElementCount
       console.log(`${current}/pageCount `)
  }}
```
