### ISSUE TITLE
Slider within container display: table

### ISSUE THREAD

**Issue by MitchWeiss** [akiran/react-slick#324]
I am trying to put my slider within a container which is being displayed as a table using CSS. This seems to completely confuse the slider and mess up its ability to set its width. 

Setting an inner container to display: block doesn't seem to mitigate the problem. 

jsfiddle: https://jsfiddle.net/fqh42hk2/1/

Any ideas why this is happening and how it can be overcome?

**Comment by MitchWeiss** [comment]
Hey @akiran, any advice to make this work?

**Comment by gjjones** [comment]
You need to set `table-layout: fixed;` on the element with `display: table;`. What it's doing in your example is sizing the table to it's contents regardless of the CSS sizing you're assigning. So instead of react-slick having constraints to size against, it thinks it has all the room in the world.

[Here is a link to the property description on MDN that talks about it in more depth.](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout)
