### ISSUE TITLE
Bug: variableWidth + infinite results in slides in wrong position...

### ISSUE THREAD

**Issue by binkydog** [akiran/react-slick#533]
Depending on the width of the container, you'll typically get the last slide showing up in the first position, or perhaps the second to last slide. Either way, it's not the first slide. 

Also, if you turn off infinite, then it works fine.  Only an issue when variableWidth and infinite enabled.

See this to reproduce: https://jsfiddle.net/a3azf02k/1/

**Comment by vorobey** [comment]
+1

**Comment by sloansparger** [comment]
+1

**Comment by miraage** [comment]
Any updates on this?

**Comment by mikeelltt** [comment]
Having the same issue 😞

**Comment by mikeelltt** [comment]
By the way, if you resize the window after the page is loaded it gets fixed, maybe it could help in fixing the bug.

**Comment by PengyuanZhao** [comment]
+1

**Comment by samahndev** [comment]
Another quick workaround for me was to do define the `ref` for the slider component and call slickGoto(1):

`
componentDidMount() {
  setTimeout(() => {
    this.slider.innerSlider.slickGoTo(1);
  }, 0);
}
`

Had to use zero setTimeout because I wanted to make sure that the slider gets fully initialised.

You can similarly call `this.slider.slickNext()`.

**Comment by laveesingh** [comment]
Similar problems have been fixed in previous releases. Please feel free to request reopen if disagree.
