### ISSUE TITLE
Custom Arrow (css property "slick-disabled")

### ISSUE THREAD

**Issue by malte1989** [akiran/react-slick#663]
### Guidlines for posting new issue

I replaced the Arrows with custom arrows like in docs mentioned. All works fine, Clicking etc.
But I want to use the css property "slick-disabled" which isn't availeable when I replace the original arrows. Is there any hint anyone can give?

  arrows: true,
  nextArrow: <NextArrow />,
  prevArrow: <PrevArrow />,

I didn't reproduced it in fiddle because it isn't really an issue or bug.

Best Regards
Malte

**Comment by akiran** [comment]
CustomArrow component will receive className as a prop
https://github.com/akiran/react-slick/blob/master/examples/CustomArrows.js#L7

It will have slick-disabled className when the button should be disabled

**Comment by PaoloDiBello** [comment]
For the ones that want a way to add the disabled attribute itself you can do it with the prop className taken from the prevArrow/nextArrow

And do the following inside each component 
    disabled={className?.includes("slick-disabled")}

**Comment by rodrigovallades** [comment]
This library is not really customizable. I mean, it can be done, but it's cumbersome. This lib depends heavily on the css classnames used in the built-in theme.

If your trying to use this lib with custom components, you're going to suffer. It's doable, but it's very painful having to override the original css styles.

Instead of the `className` prop that is actually a string of classes, the "arrow component" should have access to props that indicate the state of the button. It would be much easier to compose your own custom element.
