### ISSUE TITLE
Swiping issues when infinite = false

### ISSUE THREAD

**Issue by quarklemotion** [akiran/react-slick#71]
I'm seeing the following behavior when using react-slick in non-infinite mode:

- with slidesToShow=1 and 1 item in the carousel, the div can be dragged left or right, it does not snap back.  I noticed that the jquery slick carousel does not allow swiping in this case where there are no more slides to show.
- when dragging/swiping past the beginning or end of the carousel (also slidesToShow=1, but many slides in the carousel), the carousel does not 'snap back' to the first (or last) slide, but stays dragged out of alignment.

**Comment by vramana** [comment]
@quarklemotion It is called edgefriction. I am working on it.

**Comment by vramana** [comment]
@quarklemotion Ignore my earlier comment. I misread your comment. 

I can't reproduce this on master. I tested the issue on in the example given in docs for a few cases by setting infinite to false, the slider does 'snap back' in all the cases I tested. Can you put up an example? so that I can test the issue on that.

**Comment by vramana** [comment]
Sorry again, I can reproduce this issue. When I tried previously, it seems I dragged a little too much every time. If I drag a little bit. The slide don't snap back. I will fix it in #70.

**Comment by vermillion23** [comment]
Same problem when   infinite: false,
    accessibility: true,
    swipe: true,
    swipeToSlide: true,
any solutions?
