### ISSUE TITLE
Center Mode Warping Issue

### ISSUE THREAD

**Issue by iandoe** [akiran/react-slick#72]
Hey,

I really want to use your work for a big project but the warping animation bug is really a downer. How do you think this problem can be fixed ? I can try to help by submitting a PR if you have some idea of where to start to fix this bug :)

maybe using `ReactCSSTransitionGroup` ?

Let me know, Thanks !!!

**Comment by vramana** [comment]
@iandoe Are you refering flicker that happens at the start and end slide? I think the problem slick-center transform is applied two times due to two `setState` changes. A probable solution is to apply `.slick-center` to both the cloned slide and actual slide at the same time. I didn't try it out yet.

**Comment by dramoturg** [comment]
Hi, this problem is still active
you do not understand it?

**Comment by puglyfe** [comment]
i opened a PR for this - [#210](https://github.com/akiran/react-slick/pull/210)
