### ISSUE TITLE
Resizing browser windows breaks the slider

### ISSUE THREAD

**Issue by emzero** [akiran/react-slick#775]
1. Go to https://jsfiddle.net/kirana/20bumb4g/
2. Resize the width of the window
3. The container grows in height and the slider doesn't work anymore.

**Comment by andrewdc92** [comment]
anecdotally this does not/has not occurred in production.

**Comment by emzero** [comment]
So it's a jsfiddle thing?

**Comment by andrewdc92** [comment]
It looks that way, I have the component configured to pretty much match some of the example demos, the images remain full size within their container and the arrow buttons still work regardless of screen size. I'm not utilizing the responsive prop but the arrows are custom buttons.

**Comment by kingtran2112** [comment]
I have same problem, when resizing the browser, option autoplay is stop

**Comment by andrewdc92** [comment]
Ah interesting. I'm not using autoplay as a prop

**Comment by BKD-Digital** [comment]
Man would I love if everyone used labels so that we can actually and easily see a real bug list vs 'unlabeled' tickets that we have to sift through.

**Comment by alexiusp** [comment]
The bug with resizing occurs not only in jsFiddle. Every resizing breaks the slider layout. The width of the slide is set to something like maxInt: `width: 3.35544e+07px;`

**Comment by andrewdc92** [comment]
I have the slider wrapped in a container, gave the slide imgs a max height and set the width in ems. It preserves the functionality of the arrows and does not distort the images >600px screen size. Admittedly I just switched to react-images though, only because it has a nice pop-out full screen modal feature built in, which handles many of the img scaling issues nicely and better suits the projects needs. https://jossmac.github.io/react-images/#images

**Comment by akiran** [comment]
Issues with autoplay on resize are fixed with #651
