### ISSUE TITLE
Remove unneeded customProps next/prev arrows causing unknown props warning on arrows.js

### ISSUE THREAD

**Issue by Dajust** [akiran/react-slick#780]
arrows.js currently batches some `currentSlide` and `slideCount` custom props to the passed custom next/prev elements.
But it appears that these custom props are not needed anywhere as the sliders work pretty fine without them. 
Also, this is not proper since React forbids you from passing custom props to React Elements, thus throws ` Warning: Unknown props "currentSlide", "slideCount" ` when using custom next/prev arrows.

If you need any help, I'll be glad to PR.

**Comment by akiran** [comment]
This issue is fixed

**Comment by barefootChild** [comment]
This problem is still there!

**Comment by akiran** [comment]
if you are using custom arrow, you have to filter these props before passing to elements

**Comment by barefootChild** [comment]
How to do it? could you give some detail?

**Comment by eliseumds** [comment]
How is this fixed? We're still not able to pass custom components as arrows, only custom elements:

https://github.com/akiran/react-slick/blob/fc9e380c3fdeb766e15f28980a8b24025bbb0994/src/arrows.js#L72-L74

If it's a function, it should call `React.createElement` instead of `React.cloneElement`. It might work in the demo [CustomArrows.js](https://github.com/akiran/react-slick/blob/master/examples/CustomArrows.js) but it's definitely unexpected and already led to various issues on this repository.
