### ISSUE TITLE
Pausing autoplay via props doesn't work

### ISSUE THREAD

**Issue by pyaesone17** [akiran/react-slick#864]
When changing autoplay via props doesn't work

**Comment by jhixson** [comment]
I ran into this as well when trying to integrate it into a redux project. I was able to work around it by adding this to my component:

```
componentDidUpdate() {
  this.refs.slider.innerSlider.autoPlay();
}
```
(Assuming your slider component has the ref "slider")

**Comment by idclev31** [comment]
+1

**Comment by acontreras89** [comment]
The problem seems to be found in `componentWillReceiveProps` method of `InnerSlider`. It [updates with the next props](https://github.com/akiran/react-slick/blob/master/src/inner-slider.js#L100), but `autoPlay` [performs a check on current props](https://github.com/akiran/react-slick/blob/master/src/mixins/helpers.js#L339).

**Comment by akiran** [comment]
same #995
