### ISSUE TITLE
Error: matchMedia not present, legacy browsers require a polyfill

### ISSUE THREAD

**Issue by jaykch** [akiran/react-slick#920]
Get this error while running yarn build using react-snapshot in create-react-app

**Comment by akiran** [comment]
You can check the test setup in this project
https://github.com/akiran/react-slick/blob/master/test-setup.js

**Comment by dschinkel** [comment]
what's up with that?  I just updated to React 16.  Why should our app crash due to the fact that we don't run your tests?  I get that error too and I don't care about the tests that are in react-slick

**Comment by zernabhussain** [comment]
check this: https://github.com/akiran/react-slick/issues/742#issuecomment-557793922

**Comment by zhuber** [comment]
@zernabhussain this appears to be the same link to polyfils for unit tests, but that is not the issue. This package is breaking production apps for legacy browsers and it should not have anything to do with the test suite.

This is not working and all docs seem to point to fixing unit tests. This is actually breaking our app for IE users who are simply loading the app via browser. I think maybe the real issue is being lost along the way due to the fact that the larger issues happen outside of the testing suite.

# Steps to replicate:
1. Open Internet Explorer 9
2. View a react-slick gallery
3. Notice your app is broken
