### ISSUE TITLE
force fit `slidesToShow` if `slidesToShow > slideCount`

### ISSUE THREAD

**Issue by laveesingh** [akiran/react-slick#982]
If `slidesToShow > slideCount`, make `slidesToShow = slideCount` and throw a warning.
Also, throw a warning if `centerMode` is true and `slidesToScroll > 1`.

**Comment by laveesingh** [comment]
implemented unslick to handle this

**Comment by MichaelCastelbuono** [comment]
I just recently updated to version 0.20.0 from 0.15.4 and I believe this caused a big change in how we're using this library, and I'm wondering if you have any suggestions.

Our use case is that we still want the slides to show width/height based on the `slidesToShow` setting, but now if the `slidesToShow > slideCount` it will make the slides a lot bigger. In our case it went from dividing it up by 4 to 2 so now our slides are twice as big. Keep in mind we our working with CMS content, so we can't always guarantee a full 4 slides, which is why some pages only have 1 or 2. 

One thing that could help is to add a `unslick` class somewhere (probably the top wrapper), so we could style appropriately under those circumstances, but it will also be useful to have the `slidesToShow` number in a class or data attribute so we could target specific CSS rules for responsive cases.
